#!/usr/bin/perl -w

use strict;
use Getopt::Long;
use Net::XMPP;

my $username;
my $password;
my @rcpt;
my $body = '';

GetOptions('user=s' => \$username, 'pass=s' => \$password, 'rcpt=s@' => \@rcpt);

my $resource = "Panoptes";
my $hostname = 'talk.google.com';
my $port = 5222;
my $componentname = 'gmail.com';
my $connectiontype = 'tcpip';
my $tls = 1;

while(<STDIN>) {
    $body .= $_;
}

my $Connection = new Net::XMPP::Client();

my $status = $Connection->Connect(
       hostname => $hostname, port => $port,
       componentname => $componentname,
       connectiontype => $connectiontype, tls => $tls);

if (!(defined($status))) {
   print "ERROR:  XMPP connection failed.\n";
   print "        ($!)\n";
   exit(0);
}

my $sid = $Connection->{SESSION}->{id};
$Connection->{STREAM}->{SIDS}->{$sid}->{hostname} = $componentname;

my @result = $Connection->AuthSend(
       username => $username, password => $password,
       resource => $resource);

if ($result[0] ne "ok") {
   print "ERROR: Authorization failed: $result[0] - $result[1]\n";
   exit(0);
}

foreach my $r (@rcpt) {
    $Connection->MessageSend(
           to => $r, body => $body,
           resource => $resource
    );
}
